version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      # Load environment variables from a file
      # Developers need to create a .env file in the frontend root
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - ./frontend/dist:/usr/share/nginx/html  # Mount built files
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf  # Custom Nginx config
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
    environment:
      # Load environment variables from a file
      # Developers need to create a .env file in the frontend root
      - FLASK_ENV=${FLASK_ENV:-development}
    volumes:
      - ./backend:/app
      - data:/app/data
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "src.app:app"]


  metadata_updater:
    build:
      context: ./backend
      dockerfile: Dockerfile.cron
    volumes:
      - ./backend:/app
      - data:/app/data

volumes:
  data:
    driver: local
